export interface ListItem {
  id: number;
  title: string;
  completed: boolean;
}

export const LIST_100_ITEMS: ListItem[] = [
  { id: 1, title: "Get married", completed: false },
  { id: 2, title: "Own a house", completed: false },
  { id: 3, title: "Own a car", completed: false },
  { id: 4, title: "Learn how to drive a car", completed: false },
  { id: 5, title: "Visit the Amazon rainforest", completed: false },
  { id: 6, title: "Go on a road trip", completed: true },
  { id: 7, title: "Camp outside in a forest", completed: false },
  { id: 8, title: "Run the NYC Marathon", completed: false },
  { id: 9, title: "Run 100 km in one go", completed: false },
  { id: 10, title: "Complete a marathon in under 3 hours", completed: false },
  { id: 11, title: "Learn to swim", completed: true },
  { id: 12, title: "Take my parents on a flight", completed: false },
  { id: 13, title: "Produce a song", completed: false },
  { id: 14, title: "Own a personal music room filled with instruments", completed: false },
  { id: 15, title: "Read 1,000 books", completed: false },
  { id: 16, title: "Make 25 free throws in a row", completed: false },
  { id: 17, title: "Play a full team basketball match", completed: false },
  { id: 18, title: "Score a goal in a football match", completed: true },
  { id: 19, title: "Achieve under 10% body fat at 75+ kg body weight", completed: false },
  { id: 20, title: "Teach a class for an entire term", completed: false },
  { id: 21, title: "Perform a properly choreographed dance to a song", completed: false },
  { id: 22, title: "Learn to play NEON", completed: false },
  { id: 23, title: "Learn to play the piano", completed: false },
  { id: 24, title: "Learn to play the drums", completed: false },
  { id: 25, title: "Visit all 7 continents", completed: false },
  { id: 26, title: "Learn a new language fluently", completed: false },
  { id: 27, title: "Write a book", completed: false },
  { id: 28, title: "Start a successful business", completed: false },
  { id: 29, title: "Give a TED talk", completed: false },
  { id: 30, title: "Learn to cook 50 different dishes", completed: false },
  { id: 31, title: "Volunteer for a year", completed: false },
  { id: 32, title: "Learn to surf", completed: false },
  { id: 33, title: "Go skydiving", completed: false },
  { id: 34, title: "Climb a mountain", completed: false },
  { id: 35, title: "Learn photography professionally", completed: false },
  { id: 36, title: "Build a treehouse", completed: false },
  { id: 37, title: "Go on a solo trip", completed: false },
  { id: 38, title: "Mentor 10 people", completed: false },
  { id: 39, title: "Create a YouTube channel", completed: false },
  { id: 40, title: "Learn martial arts", completed: false },
  { id: 41, title: "Go on a safari", completed: false },
  { id: 42, title: "Learn to sail", completed: false },
  { id: 43, title: "Visit the Northern Lights", completed: false },
  { id: 44, title: "Learn calligraphy", completed: false },
  { id: 45, title: "Build a piece of furniture", completed: false },
  { id: 46, title: "Learn to meditate daily for a year", completed: false },
  { id: 47, title: "Run a half marathon", completed: false },
  { id: 48, title: "Learn to scuba dive", completed: false },
  { id: 49, title: "Plant 1,000 trees", completed: false },
  { id: 50, title: "Learn to paint", completed: false },
  { id: 51, title: "Visit 50 countries", completed: false },
  { id: 52, title: "Learn to bake bread from scratch", completed: false },
  { id: 53, title: "Complete a triathlon", completed: false },
  { id: 54, title: "Learn astronomy", completed: false },
  { id: 55, title: "Build a website from scratch", completed: true },
  { id: 56, title: "Learn to ride a motorcycle", completed: false },
  { id: 57, title: "Go whale watching", completed: false },
  { id: 58, title: "Learn to juggle", completed: false },
  { id: 59, title: "Visit the Great Wall of China", completed: false },
  { id: 60, title: "Learn to knit", completed: false },
  { id: 61, title: "Go bungee jumping", completed: false },
  { id: 62, title: "Learn to rock climb", completed: false },
  { id: 63, title: "Visit Machu Picchu", completed: false },
  { id: 64, title: "Learn to ski", completed: false },
  { id: 65, title: "Go on a hot air balloon ride", completed: false },
  { id: 66, title: "Learn to ice skate", completed: true },
  { id: 67, title: "Visit the Pyramids of Egypt", completed: false },
  { id: 68, title: "Learn to draw portraits", completed: false },
  { id: 69, title: "Go zip-lining", completed: false },
  { id: 70, title: "Learn to make pottery", completed: false },
  { id: 71, title: "Visit the Taj Mahal", completed: false },
  { id: 72, title: "Learn to do a handstand", completed: false },
  { id: 73, title: "Go camping in the desert", completed: false },
  { id: 74, title: "Learn to make sushi", completed: false },
  { id: 75, title: "Visit Antarctica", completed: false },
  { id: 76, title: "Learn to do magic tricks", completed: false },
  { id: 77, title: "Go paragliding", completed: false },
  { id: 78, title: "Learn to fix a car", completed: false },
  { id: 79, title: "Visit the Grand Canyon", completed: false },
  { id: 80, title: "Learn to make cheese", completed: false },
  { id: 81, title: "Go on a cruise", completed: false },
  { id: 82, title: "Learn to do yoga", completed: false },
  { id: 83, title: "Visit Petra", completed: false },
  { id: 84, title: "Host a house party", completed: false },
  { id: 85, title: "Go white water rafting", completed: false },
  { id: 86, title: "Learn to box", completed: false },
  { id: 87, title: "Visit Santorini", completed: false },
  { id: 88, title: "Reach an 1800 rating in chess", completed: false },
  { id: 89, title: "Go horseback riding", completed: false },
  { id: 90, title: "Learn to do parkour", completed: false },
  { id: 91, title: "Visit the Maldives", completed: false },
  { id: 92, title: "Have a pet dog (deku)", completed: false },
  { id: 93, title: "Go caving", completed: false },
  { id: 94, title: "Make a short film", completed: false },
  { id: 95, title: "Visit Iceland", completed: false },
  { id: 96, title: "Learn cinematography", completed: false },
  { id: 97, title: "Go on a helicopter ride", completed: false },
  { id: 98, title: "Learn to do backflips", completed: false },
  { id: 99, title: "Write a book", completed: false },
  { id: 100, title: "Complete this entire list", completed: false },
];

export const LIST_100_META = {
  title: "List 100",
  subtitle: "100 things to do before I turn 100",
  createdDate: "December 2, 2025",
  totalItems: 100,
  completedItems: LIST_100_ITEMS.filter(item => item.completed).length,
};
